"""Add output path in FileConversion

Revision ID: 7371e062f2ae
Revises: 7fe081fb5101
Create Date: 2025-07-25 02:15:53.119937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7371e062f2ae"
down_revision: Union[str, Sequence[str], None] = "7fe081fb5101"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_conversions", sa.Column("output_file_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_conversions", "output_file_path")
    # ### end Alembic commands ###
